
meta_title: "Dans La Musette"
meta_description: "Le cyclisme à la sauce Ketchup-Mayo Jaune."
meta_image: "logo.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@danslamusette" # indispensable pour les Twitter Cards
